# group_vars/all.yml
---

# LXC Container Configuration
# These variables will use the specified default values
# if no higher-precedence variable (e.g., from Semaphore CLI args or Variable Group) is provided.
vmid: "{{ vmid | default(8006) }}"
hostname: "{{ hostname | default('demo-ct-overlay') }}"
ostemplate: "{{ ostemplate | default('vm-overlay-template-lxc.tar.zst') }}"
storage: "{{ storage | default('proxmox-shared-B1') }}"
rootfs_size: "{{ rootfs_size | default('5G') }}"
cores: "{{ cores | default(1) }}"
memory: "{{ memory | default(256) }}"
password: "{{ password | default('Alcateldc') }}" # <-- IMPORTANT: Change this for production!
node: "{{ node | default('HP-A1-DL380') }}"

# Default network interfaces for the container.
# If a 'network_interfaces' variable is provided from a higher precedence source
# (like Semaphore CLI args or Variable Group), this entire list will be replaced.
network_interfaces:
  - name: eth0
    bridge: vmbr0
    ip: "100.124.171.169/23"
    gateway: "100.124.170.1"
    nameserver: "10.171.0.1"
    nameserver2: "10.171.0.2"
  - name: eth1
    bridge: br_pri
    ip: "20.10.10.100/24"
    gateway: "20.10.10.1"
  - name: eth2
    bridge: br_pri
    ip: "20.10.10.101/24"
    gateway: "20.10.10.1"
  - name: eth3
    bridge: br_ixr_410
    ip: "40.10.10.100/24"
    gateway: "40.10.10.1"
  - name: eth4
    bridge: br_ixr_420
    ip: "40.10.20.100/24"
    gateway: "40.10.20.1"
  - name: eth5
    bridge: br_ixr_510
    ip: "50.10.10.100/24"
    gateway: "50.10.10.1"
    nameserver: "10.171.0.1"
    nameserver2: "10.171.0.2"
  - name: eth6
    bridge: br_ixr_520
    ip: "50.10.20.1/24"
    gateway: "50.10.20.1"
    nameserver: "10.171.0.1"
